<p>
	<a class="art-button" href="/entiteit/logo">Logo</a>
</p>
<?php
if (!empty($this->messages)){
	echo "<div id='message'>" . $this->messages . "</div>";
};
?>
<div id="entiteittabs">
	<ul>
		<li><a href="tabs-1"><?php echo $this->entiteit['ent_naam']?></a></li>
	</ul>
	<div id="tabs-1">
		<h3>Details</h3>
		<?php echo $this->form;?>
	</div>
</div>
<?php echo $this->tabContainer('entiteittabs')?>