<?php
if (!empty($this->messages)){
	echo "<div id='message'>" . $this->messages . "</div>";
};
?>
<p><a class="nav" href="<?php echo $this->url(array('controller' => 'afrek', 'action' => 'add'), 'default', true);?>">Aankooprekening toevoegen</a></p>
<table id="list">
	<thead>
	<tr>
	<th>Omschrijving</th>
	<th>Verwijderen</th>
	<th>Aanpassen</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $this->afrek as $afrek ) : ?>
            <tr>
            <td><?php echo $afrek->afrek_oms; ?></td>
            <td><a href="<?php echo $this->url(array('controller' => 'afrek', 'action' => 'delete', 'afrek_id' => $groep->afrek_id), 'default', true);?>" class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" title="Verwijderen"><span class="ui-icon ui-icon-trash"></span>Verwijderen</a></td>
            <td><a href="<?php echo $this->url(array('controller' => 'afrek', 'action' => 'update', 'afrek_id' => $groep->afrek_id), 'default', true);?>" class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" title="Aanpassen"><span class="ui-icon ui-icon-pencil"></span>Aanpassen</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<p>Totaal aantal aankooprekeningen: <b><?php echo $this->afrekcount;?></b></p>