
<div id="offerteklantfiche">
	<ul>
		<li><a href="#tabs-1">Klant</a></li>
	</ul>
	<div id="tabs-1">
		<table>
			<tr>
				<td><a href="<?php echo $this->url; ?>/vf/zoekklant/doc/<?php echo $this->doc; ?>" class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" title="Zoek klant"><span class="ui-icon ui-icon-person"></span>Zoek klant</a></td>
				<td></td>
			</tr>
			<tr>
				<td>Naam:</td>
				<td><?php echo $this->klant[kl_naam1] ;?></td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo $this->klant[kl_naam2] ;?></td>
			</tr>
			<tr>
				<td>Adres:</td>
				<td><?php echo $this->klant[kl_adres1]; ?></td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo $this->klant[kl_adres2] ;?></td>
			</tr>
			<tr>
				<td>Woonplaats:</td>
				<td><?php echo $this->klant[kl_post] ;?> <?php echo $this->klant[kl_woon] ;?></td>
			</tr>
			<tr>
				<td>Land:</td>
				<td><?php echo $this->klant[kl_land] ;?></td>
			</tr>
		</table>
	</div>
</div>
<div id="offerteitemfiche">
	<ul>
		<li><a href="#tabs-1">Items</a></li>
	</ul>
	<div id="tabs-1">
		<table>
			<tr>
				<td>
					<a href="<?php echo $this->url; ?>/offerte/zoekitem/" class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" title="Zoek item"><span class="ui-icon ui-icon-circle-zoomin"></span>Zoek item</a>
				</td>
			</tr>
		</table>
	</div>
</div>
<?php echo $this->tabContainer('offerteklantfiche'); ?>
<?php echo $this->tabContainer('offerteitemfiche'); ?>