<?php
if (!empty($this->messages)){
	echo "<div id='message'>" . $this->messages . "</div>";
};
?>
<table id="list">
	<thead>
	<tr>
	<th>Actief</th>
	<th>Taal</th>
	<th>Naam</th>
	<th>Adres</th>
	<th>Postcode</th>
	<th>Woonplaats</th>
	<th>Selecteer</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $this->klant as $klant ) : ?>
            <tr>
            <td><?php echo $klant->kl_actief; ?></td>
            <td><?php echo $klant->kl_taal; ?></td>
            <td><?php echo $klant->kl_naam1; ?></td>
            <td><?php echo $klant->kl_adres1; ?></td>
            <td><?php echo $klant->kl_post; ?></td>
            <td><?php echo $klant->kl_woon; ?></td>
            <?php switch ($this->doc){
            	case "Offerte":
            		echo "<td><a href=" . $this->url . "/vf/offerte/kl_id/" . $klant->kl_id . " class=\"fg-button ui-state-default fg-button-icon-solo ui-corner-all\" title=\"Selecteren\"><span class=\"ui-icon ui-icon-check\"></span>Selecteren</a></td>";
            }?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<p>Totaal aantal klanten: <b><?php echo $this->usercount;?></b></p>