<div id="sidebar1">
<h4>Basisgegevens</h4>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'klant', 'action' => 'index'), 'default', true) ?>">Klanten</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'artikel', 'action' => 'index'), 'default', true) ?>">Artikels</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'artikelgroep', 'action' => 'index'), 'default', true) ?>">Artikelgroepen</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller' => 'afrek', 'action' => 'index'), 'default', true);?>">Aankooprekeningen</a><br />
<h4>Gebruikers</h4>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'user', 'action' => 'userlist'), 'default', true) ?>">Gebruikers</a><br/>
</div>