<div id="sidebar1">
<h5>Basisgegevens</h5>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'klant', 'action' => 'index'), 'default', true) ?>">Klanten</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'artikel', 'action' => 'index'), 'default', true) ?>">Artikels</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'artikelgroep', 'action' => 'index'), 'default', true) ?>">Artikelgroepen</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'leveran', 'action' => 'index'), 'default', true) ?>">Leveranciers</a><br/>
<h5>Beheer</h5>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'user', 'action' => 'userlist'), 'default', true) ?>">Gebruikers</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'docnummer', 'action' => 'index'), 'default', true) ?>">Documentnummers</a><br/>
<a class="nav" href="<?php echo $this->url(array('controller'=> 'entiteit', 'action' => 'index'), 'default', true) ?>"><?php echo $this->user['ent_naam']?></a><br/>
</div>